from a_star import A_star
from motion_model import sampling_motion_model

# Design an inverse kinematic controller to drive a path generated by your online A* implementation based on
# the model you developed in step 1 of HW0. 

# The function should output translational and rotational speeds [v,w]
# that will allow the robot to achieve a target 2D position [x_t, y_t] given its current position and heading [x,y,theta].
# consider the robot's current speeds and restrict maximum velocities to v_dot=.288 m/s^2 and w_dot = 5.579 rad/s^2.
# use a sampling rate of dt = .1s.

